package store
import("database/sql";"fmt";"os";"path/filepath";"time";_ "modernc.org/sqlite")
type DB struct{*sql.DB}
type Checklist struct{ID int64 `json:"id"`;Name string `json:"name"`;Tier string `json:"tier"`;Steps string `json:"steps"`;CreatedAt time.Time `json:"created_at"`}
type Progress struct{ID int64 `json:"id"`;ChecklistID int64 `json:"checklist_id"`;UserID string `json:"user_id"`;CompletedSteps string `json:"completed_steps"`;Percent int `json:"percent"`;UpdatedAt time.Time `json:"updated_at"`}
func Open(d string)(*DB,error){os.MkdirAll(d,0755);dsn:=filepath.Join(d,"concierge.db")+"?_journal_mode=WAL&_busy_timeout=5000";db,err:=sql.Open("sqlite",dsn);if err!=nil{return nil,fmt.Errorf("open: %w",err)};db.SetMaxOpenConns(1);migrate(db);return &DB{db},nil}
func migrate(db *sql.DB){db.Exec(`CREATE TABLE IF NOT EXISTS checklists(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,tier TEXT DEFAULT 'free',steps TEXT DEFAULT '',created_at DATETIME DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS progress(id INTEGER PRIMARY KEY AUTOINCREMENT,checklist_id INTEGER NOT NULL,user_id TEXT NOT NULL,completed_steps TEXT DEFAULT '',percent INTEGER DEFAULT 0,updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,UNIQUE(checklist_id,user_id))`)}
func(db *DB)Create(c *Checklist)error{res,err:=db.Exec(`INSERT INTO checklists(name,tier,steps)VALUES(?,?,?)`,c.Name,c.Tier,c.Steps);if err!=nil{return err};c.ID,_=res.LastInsertId();return nil}
func(db *DB)List()([]Checklist,error){rows,_:=db.Query(`SELECT id,name,tier,steps,created_at FROM checklists ORDER BY name`);defer rows.Close();var out[]Checklist;for rows.Next(){var c Checklist;rows.Scan(&c.ID,&c.Name,&c.Tier,&c.Steps,&c.CreatedAt);out=append(out,c)};return out,nil}
func(db *DB)UpdateProgress(checklistID int64,userID,completedSteps string,pct int){db.Exec(`INSERT INTO progress(checklist_id,user_id,completed_steps,percent,updated_at)VALUES(?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(checklist_id,user_id) DO UPDATE SET completed_steps=excluded.completed_steps,percent=excluded.percent,updated_at=CURRENT_TIMESTAMP`,checklistID,userID,completedSteps,pct)}
func(db *DB)GetProgress(checklistID int64,userID string)(*Progress,error){var p Progress;err:=db.QueryRow(`SELECT id,checklist_id,user_id,completed_steps,percent,updated_at FROM progress WHERE checklist_id=? AND user_id=?`,checklistID,userID).Scan(&p.ID,&p.ChecklistID,&p.UserID,&p.CompletedSteps,&p.Percent,&p.UpdatedAt);if err!=nil{return &Progress{ChecklistID:checklistID,UserID:userID,Percent:0},nil};return &p,nil}
func(db *DB)Delete(id int64){db.Exec(`DELETE FROM progress WHERE checklist_id=?`,id);db.Exec(`DELETE FROM checklists WHERE id=?`,id)}
func(db *DB)Stats()(map[string]interface{},error){var checklists,users int;db.QueryRow(`SELECT COUNT(*) FROM checklists`).Scan(&checklists);db.QueryRow(`SELECT COUNT(DISTINCT user_id) FROM progress`).Scan(&users);return map[string]interface{}{"checklists":checklists,"tracked_users":users},nil}
